services:
  postgres:
    image: postgres:17
    container_name: langroute-db-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC
    ports:
      - '5432:5432'
    volumes:
      - langroute_pgdata_prod:/var/lib/postgresql/data
    networks:
      - langroute-net-prod
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 30s
      timeout: 10s
      retries: 3

  nextjs:
    build:
      dockerfile: docker/Dockerfile.prod
    image: langroute-app-prod:latest
    container_name: langroute-app-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - langroute-net-prod

volumes:
  langroute_pgdata_prod:

networks:
  langroute-net-prod:
    driver: bridge 